export const genres = [
  "4-Koma",
  "Action",
  "Adventure",
  "Aliens",
  "Anthology",
  "Boys' Love",
  "Comedy",
  "Cooking",
  "Crime",
  "Delinquents",
  "Demons",
  "Drama",
  "Doujinshi",
  "Fantasy",
  "Full Color",
  "Genderswap",
  "Ghosts",
  "Girls' Love",
  "Gore",
  "Harem",
  "Historical",
  "Horror",
  "Isekai",
  "Loli",
  "Long Strip",
  "Magic",
  "Magical Girls",
  "Mafia",
  "Martial Arts",
  "Medical",
  "Mecha",
  "Military",
  "Monsters",
  "Music",
  "Mystery",
  "Ninja",
  "Official Colored",
  "Oneshot",
  "Philosophical",
  "Police",
  "Post-Apocalyptic",
  "Psychological",
  "Romance",
  "Samurai",
  "School Life",
  "Sci-Fi",
  "Self-Published",
  "Sexual Violence",
  "Slice of Life",
  "Sports",
  "Superhero",
  "Supernatural",
  "Survival",
  "Thriller",
  "Time Travel",
  "Tragedy",
  "Traditional Games",
  "Vampires",
  "Video Games",
  "Virtual Reality",
  "Web Comic",
  "Wuxia",
  "Zombies",
  "Adaptation",
  "Animals",
  "Award Winning",
  "Crossdressing",
  "Fan Colored",
  "Incest",
  "Office Workers",
  "Reverse Harem",
  "Villainess",
  "Monster Girls",
  "Shota",
  "Gyaru",
];
